# Generated by Django 2.2 on 2019-11-18 08:25

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='details',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='step',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField(default=0)),
                ('details', jsonfield.fields.JSONField(default=dict, max_length=8192)),
                ('completed', models.BooleanField(default=False)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Respondent')),
            ],
        ),
    ]
