# Generated by Django 2.2 on 2019-11-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20191118_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.Respondent'),
        ),
    ]
